-- Development seed data for the reports table.
-- Intended for local/dev environments only.

INSERT INTO reports (
    title,
    description,
    report_type,
    status,
    player_email,
    player_name,
    screenshot_path,
    screenshot_mime_type,
    screenshot_size_bytes,
    source,
    priority,
    tags,
    created_at,
    updated_at,
    closed_at
) VALUES
(
    'Player falls through map near Frostpeak bridge',
    'When sprinting and rolling near the broken planks by Frostpeak bridge, the player clips through the terrain and cannot recover without a respawn.',
    'bug',
    'open',
    'arlen.wright@example.com',
    'ArlenW',
    'uploads/example_bug.png',
    'image/png',
    254321,
    'web',
    1,
    ARRAY['graphics', 'performance'],
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '3 days',
    NULL
),
(
    'Crash when entering portal in Crystal Cavern',
    'Client consistently crashes to desktop when stepping into the third portal in Crystal Cavern after defeating the miniboss.',
    'bug',
    'investigating',
    'sylvia.cho@example.com',
    'Sylv',
    'uploads/portal_crash.png',
    'image/png',
    387445,
    'web',
    1,
    ARRAY['performance', 'graphics'],
    NOW() - INTERVAL '2 days 6 hours',
    NOW() - INTERVAL '1 day 4 hours',
    NULL
),
(
    'Bow animation desync in co-op',
    'In co-op, remote players see the bow draw animation complete early, causing arrows to appear to fire before full charge.',
    'bug',
    'closed',
    NULL,
    'KiteRunner',
    NULL,
    NULL,
    NULL,
    'web',
    2,
    ARRAY['combat', 'ui'],
    NOW() - INTERVAL '8 days',
    NOW() - INTERVAL '6 days',
    NOW() - INTERVAL '6 days'
),
(
    'Add an optional minimap overlay',
    'A small minimap in the corner would help navigation in dense forest areas where landmarks are hard to track.',
    'suggestion',
    'open',
    'nina.valdez@example.com',
    NULL,
    NULL,
    NULL,
    NULL,
    'web',
    3,
    ARRAY['ui'],
    NOW() - INTERVAL '20 hours',
    NOW() - INTERVAL '20 hours',
    NULL
),
(
    'Allow remapping all controls on gamepad',
    'Please allow full remapping for gamepad buttons, especially dodge and interact, to improve accessibility.',
    'suggestion',
    'investigating',
    NULL,
    'AdaptiveAce',
    NULL,
    NULL,
    NULL,
    'web',
    2,
    ARRAY['controls', 'ui'],
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '4 days 12 hours',
    NULL
),
(
    'Add additional difficulty levels above hard',
    'Veteran players would love an extra nightmare mode with smarter enemy AI and reduced healing drops.',
    'suggestion',
    'closed',
    'mikael.ross@example.com',
    'MikaelR',
    NULL,
    NULL,
    NULL,
    'web',
    4,
    ARRAY['balance'],
    NOW() - INTERVAL '14 days',
    NOW() - INTERVAL '11 days',
    NOW() - INTERVAL '11 days'
),
(
    'Fire arrows are too strong in arena matches',
    'Fire arrows can delete heavy armor builds in two hits even without full charge, making other arrow types irrelevant.',
    'balance_issue',
    'open',
    'jorge.tan@example.com',
    'JTan',
    'uploads/fire_arrow_balance.png',
    'image/png',
    198203,
    'web',
    1,
    ARRAY['combat', 'balance'],
    NOW() - INTERVAL '10 hours',
    NOW() - INTERVAL '10 hours',
    NULL
),
(
    'Electric bow damage scales too high with crit chance',
    'Electric bow damage appears to double dip on crit multipliers after patch 1.3, especially in endgame gear sets.',
    'balance_issue',
    'investigating',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'web',
    1,
    ARRAY['combat', 'balance', 'performance'],
    NOW() - INTERVAL '1 day 8 hours',
    NOW() - INTERVAL '1 day',
    NULL
),
(
    'Enemy shield regeneration outpaces melee builds',
    'Elite sentinels recover shields so quickly that slower melee builds cannot meaningfully break through.',
    'balance_issue',
    'closed',
    'lena.ford@example.com',
    'LenaF',
    NULL,
    NULL,
    NULL,
    'web',
    2,
    ARRAY['combat', 'balance'],
    NOW() - INTERVAL '12 days',
    NOW() - INTERVAL '9 days',
    NOW() - INTERVAL '9 days'
),
(
    'HUD elements overlap at 16:10 resolution',
    'Quest tracker and stamina bar overlap when running the game at 1680x1050, making objective text unreadable.',
    'bug',
    'open',
    NULL,
    'RoguePixel',
    'uploads/hud_overlap.png',
    'image/png',
    142908,
    'web',
    2,
    ARRAY['ui', 'graphics'],
    NOW() - INTERVAL '7 hours',
    NOW() - INTERVAL '7 hours',
    NULL
),
(
    'Add colorblind accessibility presets',
    'Preset color palettes for deuteranopia/protanopia would make enemy telegraphs and loot rarity easier to distinguish.',
    'suggestion',
    'open',
    'owen.gray@example.com',
    'OGray',
    NULL,
    NULL,
    NULL,
    'web',
    3,
    ARRAY['ui', 'controls'],
    NOW() - INTERVAL '2 days 3 hours',
    NOW() - INTERVAL '2 days 3 hours',
    NULL
),
(
    'Frame drops during rainstorms in capital city',
    'Severe frame-time spikes occur during heavy rain in the capital district, especially near market stalls.',
    'bug',
    'investigating',
    'cami.reed@example.com',
    NULL,
    NULL,
    NULL,
    NULL,
    'web',
    1,
    ARRAY['performance', 'graphics'],
    NOW() - INTERVAL '4 days 5 hours',
    NOW() - INTERVAL '2 days',
    NULL
);
